# Generated by Django 3.2.5 on 2021-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournaments', to='players.Team'),
        ),
    ]
