# Generated by Django 3.2.5 on 2021-08-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_tournament_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.sponsor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='teams',
            field=models.ManyToManyField(related_name='sponsors', through='players.Sponsorship', to='players.Team'),
        ),
    ]
